version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: puntos_point_development
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0 -p 4000"
    volumes:
      - .:/rails
      - storage:/rails/storage
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/puntos_point_development
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      SMTP_URL: smtp://mailcatcher:1025

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/puntos_point_development
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      SMTP_URL: smtp://mailcatcher:1025
    volumes:
      - .:/rails
      - storage:/rails/storage

volumes:
  db-data:
  storage: